### ISSUE TITLE
No HTML output with websocket load test

### ISSUE THREAD

**Issue by CyriacBr** [clinicjs/node-clinic#275]
## Expected Behavior
After running these commands:
* `clinic doctor -- node main.js`
* `artillery run load-test.yaml`
Clinicjs should generate a HTML file.
Artillery is a CLI similar to autocannon, but that supports websockets.
I guess it's not working because it's not using autocannon?

## Current Behavior
This is what is generated:
* `30188.clinic-doctor-processstat`
* `30188.clinic-doctor-systeminfo`
* `30188.clinic-doctor-traceevent`

## Steps to Reproduce (for bugs)
I use `artillery` to load test my WS based nodejs server.
1. Run clinic
`clinic doctor -- node main.js`
2. Run artillery with the following config file:
```yaml
config:
  target: "http://localhost:3000"
  socketio:
    transports: ["websocket"]
  phases:
    - duration: 60
      arrivalRate: 5
scenarios:
  - name: "Connect and send a bunch of messages"
    engine: "socketio"
    flow:
      - loop:
          - emit:
              channel: EVENT_NAME
              data: JSON_PAYLOAD
          - think: 1
        count: 5
```
3. `artillery run load-test.yaml`

## Sample upload

Well I actually tried but `clinic upload` does nothing but displays help.

## Environment
* Clinic.js version: 8.0.1
* Doctor version: 7.0.1
* Node.js version: 12.17.0
* Operating system and version: Windows 10
